// CREATE: Notification Object
// Adds a new notification to the notifID collection in the notifications bucket
// This notification was generated by the userID
export const createNotification = (data) => {
    console.log('Create Notif Action');
    const { userID, drinkID, type, notifID, comment } = data;
    return async (dispatch, getState, { getFirebase }) => {
        const firebase = await getFirebase();
        const firestore = await firebase.firestore();

        const date = new Date();

        // Current Comment ID
        const ref = await firestore
            .collection('notifications')
            .doc(notifID)
            .collection('allNotifications')
            .doc();
        const id = ref.id;
        console.log('Current Notif ID: ' + id);

        try {
            // Add notif to the notifs collection
            await firestore
                .collection('notifications')
                .doc(notifID)
                .collection('allNotifications')
                .doc(id)
                .set({
                    userID: userID,
                    type: type,
                    dateCreated: date.toISOString(),
                    drinkID: drinkID,
                    id: id,
                    comment: comment
                })

            dispatch({ type: 'CREATE_NOTIF', id })
        } catch (err) {
            dispatch({ type: 'CREATE_NOTIF_ERROR', err });
        }
    }
};
